services:
  - type: web
    name: websys2finalproject
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate --noinput && gunicorn core.wsgi:application
    envVars:
      - key: DJANGO_ENV
        value: "prod"
      - key: SECRET_KEY
        value: 7ssgzad3r=pd5x#(f-^pcbw==+#4+5s_-!v7np1(39(kr)h(5=
      - key: DEBUG
        value: "False"
      - key: USE_SQLITE
        value: "False"
      - key: ALLOWED_HOSTS
        value: "websys2finalproject.onrender.com, .onrender.com"
      - key: DATABASE_URL
        sync: true
