# Generated by Django 6.0.5 on 2026-08-01 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_sale_payment_saleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiration Date'),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('low_stock', 'Low Stock'), ('expiring', 'Expiring'), ('expired', 'Expired')], max_length=20, verbose_name='Type')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resolved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='product.product', verbose_name='Product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
