# Generated by Django 6.0.7 on 2026-08-01 11:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_requested',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time the user registered.', verbose_name='Date Requested'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Designates whether this user account has been approved by an administrator.', verbose_name='Approved'),
        ),
    ]
