# Generated by Django 5.2.16 on 2026-08-02 13:53
import os
from django.db import migrations
from django.contrib.auth import get_user_model
from django.core.exceptions import ImproperlyConfigured


def create_initial_admin(apps, schema_editor):
    """
    Create an initial admin user if none exists.
    Credentials are taken from environment variables for security.
    """
    User = apps.get_model('accounts', 'User')

    # Check if any users exist
    if User.objects.exists():
        return  # Users already exist, don't create another

    # Get credentials from environment variables
    username = os.environ.get('ADMIN_USERNAME', 'admin')
    email = os.environ.get('ADMIN_EMAIL', 'admin@example.com')
    password = os.environ.get('ADMIN_PASSWORD')

    # If password not set, we cannot create a user for security reasons
    # In development, we might want to allow a default, but in production this should be required
    if not password:
        # Only create a default user in development if DEBUG is True
        # We need to check settings, but we can't import settings in migrations easily
        # For safety, we'll skip creation if no password is provided
        # Admin can still create a user via other means if needed
        return

    # Create the superuser
    try:
        user = User.objects.create_superuser(
            username=username,
            email=email,
            password=password
        )
        # Explicitly set approval and role since custom save() isn't available in migrations
        user.is_approved = True
        if user.is_superuser:
            user.role = 'admin'
        user.save()
    except Exception as e:
        # Log the error but don't fail the migration
        # In a real app, you might want to use logging
        pass


def reverse_initial_admin(apps, schema_editor):
    """
    Remove the initial admin user if it was created by this migration.
    Note: This is dangerous in production as it might delete a real admin.
    We'll make it a no-op for safety.
    """
    # Intentionally left empty to prevent accidental deletion
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_activitylog'),
        ('audit', '0001_initial'),  # Ensure AuditLog table exists for signal handlers
    ]

    operations = [
        migrations.RunPython(create_initial_admin, reverse_initial_admin),
    ]
