# Generated by Django 5.2.16 on 2026-08-02 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_snapshot', models.CharField(blank=True, default='', help_text='Username stored as text in case the user account is later deleted.', max_length=150, verbose_name='Username Snapshot')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Failed Login'), ('STATUS_CHANGE', 'Status Change'), ('STOCK_ADJUSTMENT', 'Stock Adjustment'), ('PAYMENT', 'Payment'), ('OTHER', 'Other')], db_index=True, max_length=20, verbose_name='Action')),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Object ID')),
                ('object_repr', models.CharField(blank=True, default='', help_text='Human-readable string of the affected object, e.g. "Product: Sony WH-1000XM5".', max_length=255, verbose_name='Object Representation')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Structured before/after diff, e.g. {"stock_quantity": {"old": 50, "new": 45}}.', null=True, verbose_name='Changes')),
                ('description', models.TextField(blank=True, default='', help_text='Short human-readable summary of the action.', verbose_name='Description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, default='', max_length=512, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=10, verbose_name='Severity')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype', verbose_name='Content Type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user'], name='audit_log_user_idx'), models.Index(fields=['action'], name='audit_log_action_idx'), models.Index(fields=['content_type'], name='audit_log_ct_idx'), models.Index(fields=['timestamp'], name='audit_log_ts_idx')],
            },
        ),
    ]
